// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCat59UN8UHltKsW8Rp1euwXzNBlDWcAK8',
    appId: '1:917049348701:web:6752a4b7b85462425b73b4',
    messagingSenderId: '917049348701',
    projectId: 'arhomes-app',
    authDomain: 'arhomes-app.firebaseapp.com',
    storageBucket: 'arhomes-app.appspot.com',
    measurementId: 'G-1J15PT64K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBePsiZRuKv1DzpQGBqZkYhh84jtwm5pA4',
    appId: '1:917049348701:android:2335ad249240bbc55b73b4',
    messagingSenderId: '917049348701',
    projectId: 'arhomes-app',
    storageBucket: 'arhomes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2oAcAavoQpiCNvXrnzNNgBA0CAg5HbFQ',
    appId: '1:917049348701:ios:197ce8daee63af355b73b4',
    messagingSenderId: '917049348701',
    projectId: 'arhomes-app',
    storageBucket: 'arhomes-app.appspot.com',
    iosBundleId: 'com.example.arHomeDecorationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2oAcAavoQpiCNvXrnzNNgBA0CAg5HbFQ',
    appId: '1:917049348701:ios:858aafb6270498215b73b4',
    messagingSenderId: '917049348701',
    projectId: 'arhomes-app',
    storageBucket: 'arhomes-app.appspot.com',
    iosBundleId: 'com.example.arHomeDecorationApp.RunnerTests',
  );
}
